DELETE http://localhost:8080/event/cancel/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFeHBvIjoxNzUwNDk5NjM0LCJlbWFpbCI6Illhc2hfUyIsInVzZXJfaWQiOjF9.41iDSxs2FmNuWQfD7fIfT4CDout0SOXWMzwh7UWBWPQ